
modLoader = "javafml"
loaderVersion = "[4,)"

license = "Supplementaries Team License v.1.5"
issueTrackerURL = "https://github.com/MehVahdJukaar/sawmill/issues"


[[mixins]]
config = "sawmill.mixins.json"
[[mixins]]
config = "sawmill-common.mixins.json"


[[mods]]
    modId = "sawmill"
    version = "1.21-1.7.1"
    displayName = "Universal Sawmill"
    logoFile = "icon.png"
    authors = "MehVahdJukaar"
    credits = "MehVahdJukaar, Plantkillable"
    description = '''Simple, Elegant, Universal Sawmill'''
    modUrl = "https://www.curseforge.com/minecraft/mc-mods/sawmill"
    itemIcon = "minecraft:brush" #catalogue icon
    #enumExtensions="META-INF/enumextensions.json"

[[dependencies.sawmill]]
    modId = "neoforge"
    mandatory = true
    versionRange = "[4,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.sawmill]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.21,1.21.2)"
    ordering = "NONE"
    side = "BOTH"


[[dependencies.sawmill]]
    modId = "moonlight"
    mandatory = true
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"
