
modLoader = "javafml"
loaderVersion = "[4,)"

license = "Supplementaries Team License v.1.1"
issueTrackerURL = "https://github.com/MehVahdJukaar/StoneZone/issues"

[[mods]]
modId = "stonezone"
version = "1.21-2.11.5"
displayName = "Stone Zone"
logoFile = "icon.png"
authors = "Xel'Bayria, MehVahdJukaar"
credits = "MehVahdJukaar, Xel'Bayria"
description = '''Ultimate Stone Compat Mod'''
modUrl = "https://www.curseforge.com/minecraft/mc-mods/stone-zone"
itemIcon = "stonezone:all_stones" #catalogue icon

[[dependencies.stonezone]]
modId = "neoforge"
type = "required"
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stonezone]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.stonezone]]
modId = "moonlight"
type = "required"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/selene"
versionRange = "[1.21-2.23.0,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.stonezone]]
modId = "everycomp"
type = "required"
referralUrl = "https://www.curseforge.com/minecraft/mc-mods/selene"
versionRange = "[1.21-2.11.10,]"
ordering = "BEFORE"
side = "BOTH"
