# MyPy type checker configuration

python_version: "3.7"
warn_return_any: true
warn_unused_configs: true
disallow_untyped_defs: false
ignore_missing_imports: true

overrides:
  - module: tests.*
    disallow_untyped_defs: false
